remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-redirect-from

title: Music Like You Mean It

back_to_top: true
back_to_top_text: "Back to top"

exclude: ["README.md"]

color_scheme: mlymi

callouts:
  important:
    color: blue

ga_tracking: G-3WVZW84PTJ
ga_tracking_anonymize_ip: true
